steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: 
      - gcloud
      - functions
      - deploy
      - annotateAPC
      - --runtime=python37
      - --entry-point=main
      - --region=us-central1
      - --source=Serverless/annotateAPC
      - --trigger-topic=bigquery-insert-events
      - --update-env-vars=STORAGE_BUCKET=gene222_final_annotations
